### ISSUE TITLE
Suspensión de Eventos

### ISSUE THREAD

**Issue by Cramer666** [grupo1-ciu/gestion-de-eventos#5]
Epica:  Ex. `#1`

### Descripcion
**Como**  administrador,
**Quiero**  quiero suspender eventos cuando sea necesario ,  
**Para**  evitar que los usuarios se inscriban en eventos cancelados..  

### Criterios de Aceptacion
*El administrador debe poder marcar un evento como "suspendido".
*Los eventos suspendidos no deben aparecer en la lista de eventos disponibles.
*Los usuarios inscritos o inscriptos (? deben recibir una notificación sobre la suspensión.

### Tareas
- [ ] Ex. `#1` Crear opción para suspender evento.
- [ ] Ex. `#2`Actualizar estado del evento a "Suspendido".
- [ ] Ex. `#3`Excluir eventos suspendidos de la lista de eventos disponibles.
- [ ] Ex. `#4` Notificar a los usuarios inscritos sobre la suspensión del evento.
- [ ] Ex. `#5` Probar la funcionalidad.
